### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [ossilva/UH-FS19_project#1]
# Katselmointi

Terve @ossilva! Tässä lyhyt katselmointi Full Stack kurssin projektistasi [Image upload-gallery with REST API](https://github.com/ossilva/gatsby-app-starter-rest-api). 

### Mitä tein?

- Kirjauduin sisään
- Yritin ladata kuvan tägeillä
- Katsoin galleriaa
- Kirjauduin ulos

### Kokemus

- Selkeä käyttöliittymä, hyvää työtä! 🥇
- Kuvan lataaminen ei tunnu toimivan, johtaa jatkuvasti virheeseen `Error Upload Params TypeError: Cannot read property 'key' of undefined`
- Kuvan tägien muuttaminen tyhjentää lisätyt kuvat
- Galleria-sivulla ei ole sisältöä. Luultavasti johtuu siitä, etten saanut ladattua kuvaa
- Eri polkujen sivut eivät aukea suoraan selaimen osoiterivin kautta, esim. https://master.d5ayadruv5vnm.amplifyapp.com/app/gallery
- Geneerisen "React App"-titlen ja faviconin voisi muuttaa kuvaavammaksi

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä!
- Käyttäjän kirjautumisen tarkastaminen ja siihen liittyvät operaatiot on tehty ehkä hieman [likaisesti](https://github.com/ossilva/gatsby-app-starter-rest-api/blob/master/src/components/AppWrapper.js#L33). Tässä on hyvä, Gatsbyn suosima lähestymistapa ongelmaan: https://www.gatsbyjs.org/tutorial/authentication-tutorial/#controlling-private-routes
- Nimeämistä voisi hieman viilata, olisiko osuvampi nimi esim. `LoginForm`: https://github.com/ossilva/gatsby-app-starter-rest-api/blob/master/src/components/common/Form.js#L10
- Tämänkin voisi nimetä kuvaavammin, esim. `UserProvider`: https://github.com/ossilva/gatsby-app-starter-rest-api/blob/master/src/providers/Provider.js
- Lokalisoiduissa teksteissä (kuten [täällä](https://github.com/ossilva/gatsby-app-starter-rest-api/blob/master/src/components/common/Form.js#L86)) voisi harkita jonkin lokalisaatiokirjaston käyttöä, kuten [react-i18next](https://react.i18next.com/) 
- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- Reittien käsittelijöiden ainaisista `try { ... } catch (e) { next(e) }`-lohkoista pääsee helposti eroon [express-async-errors](https://www.npmjs.com/package/express-async-errors)-kirjaston avulla

## Kokonaisuus

- Suhteellisen käyttökelpoisen ja selkeän oloinen sovellus, mutta kuvien lataamisen vaikuttaisi olevan melko kriittinen bugi
- Koodi on kaikin puolin hyvin organisoitua ja sen sisäinen laatu on melko korkea. Frontend-puolella kirjautumisen vaativat reitit kannattaisi suojata jollain deklaratiivisella tavalla, kuten `PrivateRoute`-komponentilla. Myös nimeämiseen voisi kiinnittää enemmän huomiota

**Comment by ossilva** [comment]
Kiitos, katselmoinnista @Kaltsoon!. Hyviä ideoita ja vinkkejä, sekä aina tarpeellista kritiikkiä, tulevia projekteja varten. Huomasin, että et päässyt kokoeilemaan toimivaa versiota aplikaatiosta, joka löytyy osoitteesta: http://upload-gallery-backend.herokuapp.com. Pahoittelut siitä vanha osoite oli eksynyt dokumentaatioon.
